/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.Usuario;
import database.Database;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import views.Listagem;
import javax.swing.table.DefaultTableModel;
import models.Podcast;


/**
 *
 * @author Familia Brasileiro
 */
public class CadastrarPodcast extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPodcast
     */
    public CadastrarPodcast() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPodCast3 = new javax.swing.JLabel();
        lblCenaflix3 = new javax.swing.JLabel();
        lblCadastrarPodCast = new javax.swing.JLabel();
        lblProdutorCad = new javax.swing.JLabel();
        txtNomeProdutor = new javax.swing.JTextField();
        lblNomeEpsodio = new javax.swing.JLabel();
        txtNomeEpisodio = new javax.swing.JTextField();
        lblNumeroEpisodio = new javax.swing.JLabel();
        txtNumeroEpisodio = new javax.swing.JTextField();
        lblDuracao = new javax.swing.JLabel();
        txtDuracao = new javax.swing.JTextField();
        lblURL = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        btnCadastrarPod = new javax.swing.JButton();
        btnVerListagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BR Software");

        jPanel1.setBackground(new java.awt.Color(10, 8, 29));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Podcast"));

        lblPodCast3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPodCast3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PodCast.jpg"))); // NOI18N
        lblPodCast3.setToolTipText("Imagem PodCast");

        lblCenaflix3.setBackground(new java.awt.Color(0, 0, 0));
        lblCenaflix3.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblCenaflix3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCenaflix3.setText("CENAFLIX");
        lblCenaflix3.setToolTipText("CenaFlix");

        lblCadastrarPodCast.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCadastrarPodCast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastrarPodCast.setText("Cadastrar Podcast");
        lblCadastrarPodCast.setToolTipText("LISTAGEM");

        lblProdutorCad.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblProdutorCad.setForeground(new java.awt.Color(238, 86, 153));
        lblProdutorCad.setText("Produtor");
        lblProdutorCad.setToolTipText("Produtor");

        txtNomeProdutor.setBackground(new java.awt.Color(143, 205, 240));
        txtNomeProdutor.setToolTipText("Insira o nome do Produtor");
        txtNomeProdutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutorActionPerformed(evt);
            }
        });
        txtNomeProdutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeProdutorKeyPressed(evt);
            }
        });

        lblNomeEpsodio.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNomeEpsodio.setForeground(new java.awt.Color(238, 86, 153));
        lblNomeEpsodio.setText("Nome do Episódio ");
        lblNomeEpsodio.setToolTipText("Nome do Epsódio");

        txtNomeEpisodio.setBackground(new java.awt.Color(143, 205, 240));
        txtNomeEpisodio.setToolTipText("Insira o nome do Epsódio");
        txtNomeEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEpisodioActionPerformed(evt);
            }
        });
        txtNomeEpisodio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeEpisodioKeyPressed(evt);
            }
        });

        lblNumeroEpisodio.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNumeroEpisodio.setForeground(new java.awt.Color(238, 86, 153));
        lblNumeroEpisodio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumeroEpisodio.setText("Nº do Episódio ");
        lblNumeroEpisodio.setToolTipText("Digite o Nº do Episódio ");

        txtNumeroEpisodio.setBackground(new java.awt.Color(143, 205, 240));
        txtNumeroEpisodio.setToolTipText("Digite o Nº do Episódio ");
        txtNumeroEpisodio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroEpisodioKeyPressed(evt);
            }
        });

        lblDuracao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblDuracao.setForeground(new java.awt.Color(238, 86, 153));
        lblDuracao.setText("Duração");
        lblDuracao.setToolTipText("Duração");

        txtDuracao.setBackground(new java.awt.Color(143, 205, 240));
        txtDuracao.setToolTipText("Informe a Duração");
        txtDuracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDuracaoKeyPressed(evt);
            }
        });

        lblURL.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblURL.setForeground(new java.awt.Color(238, 86, 153));
        lblURL.setText("URL do repositório");
        lblURL.setToolTipText("URL do repositório");

        txtURL.setBackground(new java.awt.Color(143, 205, 240));
        txtURL.setToolTipText("URL do repositório");
        txtURL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtURLKeyPressed(evt);
            }
        });

        btnCadastrarPod.setBackground(new java.awt.Color(143, 205, 240));
        btnCadastrarPod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastrarPod.setForeground(new java.awt.Color(238, 86, 153));
        btnCadastrarPod.setText("Cadastrar");
        btnCadastrarPod.setToolTipText("Botão Cadastrar");
        btnCadastrarPod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPodActionPerformed(evt);
            }
        });
        btnCadastrarPod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarPodKeyPressed(evt);
            }
        });

        btnVerListagem.setBackground(new java.awt.Color(143, 205, 240));
        btnVerListagem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerListagem.setForeground(new java.awt.Color(238, 86, 153));
        btnVerListagem.setText("Ver Listagem");
        btnVerListagem.setToolTipText("Botão Ver Listagem");
        btnVerListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPodCast3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCenaflix3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCadastrarPodCast, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProdutorCad)
                        .addGap(262, 262, 262))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNumeroEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDuracao)
                                .addComponent(lblURL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDuracao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumeroEpisodio)
                                .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblNomeEpsodio)
                        .addComponent(btnCadastrarPod)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnVerListagem, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPodCast3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCenaflix3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblCadastrarPodCast)))
                .addGap(46, 46, 46)
                .addComponent(lblProdutorCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lblNomeEpsodio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroEpisodio)
                    .addComponent(txtNumeroEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuracao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblURL))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarPod)
                    .addComponent(btnVerListagem))
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListagemActionPerformed
        // TODO add your handling code here:Ver Listagem
       Usuario usuario = new Usuario();
        Listagem voltaListagem = new Listagem(usuario);
            voltaListagem.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnVerListagemActionPerformed

    private void btnCadastrarPodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPodActionPerformed
        // TODO add your handling code here:Cadastrar
        try{
        String nomeProdutor = txtNomeProdutor.getText();
        String nomeEpisodio = txtNomeEpisodio.getText();
        int numeroEpisodio = Integer.parseInt(txtNumeroEpisodio.getText());
        int duracao = Integer.parseInt(txtDuracao.getText());
        String url = txtURL.getText();

        Podcast novoPodcast = new Podcast(0, nomeProdutor, nomeEpisodio, numeroEpisodio, duracao, url);
        Database database = new Database(); 
        database.adicionarPodcast(novoPodcast);
        

        JOptionPane.showMessageDialog(this, "Podcast cadastrado com sucesso!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Todos os campos devem estar preenchidos\n "
              + "Ocorreu um erro ao cadastrar o podcast: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        // Limpa os campos de texto para uma nova entrada
        txtNomeProdutor.setText("");
        txtNomeEpisodio.setText("");
        txtNumeroEpisodio.setText("");
        txtDuracao.setText("");
        txtURL.setText("");
    }//GEN-LAST:event_btnCadastrarPodActionPerformed

    private void txtNomeEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEpisodioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEpisodioActionPerformed

    private void txtNomeProdutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutorActionPerformed

    private void txtNomeProdutorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutorKeyPressed
        // TODO add your handling code here: Avançar Epsodio
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtNomeEpisodio.requestFocus();
        }
    }//GEN-LAST:event_txtNomeProdutorKeyPressed

    private void txtNomeEpisodioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeEpisodioKeyPressed
        // TODO add your handling code here: Avançar N° do Episodio
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            txtNumeroEpisodio.requestFocus();
        }
    }//GEN-LAST:event_txtNomeEpisodioKeyPressed

    private void txtNumeroEpisodioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEpisodioKeyPressed
        // TODO add your handling code here: Avança para Duração
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            txtDuracao.requestFocus();
        }

    }//GEN-LAST:event_txtNumeroEpisodioKeyPressed

    private void txtDuracaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuracaoKeyPressed
        // TODO add your handling code here:Avança para URL
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            txtURL.requestFocus();
        }

    }//GEN-LAST:event_txtDuracaoKeyPressed

    private void txtURLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtURLKeyPressed
        // TODO add your handling code here: Avança para Cadastrar
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnCadastrarPod.requestFocus();
        }
    }//GEN-LAST:event_txtURLKeyPressed

    private void btnCadastrarPodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarPodKeyPressed
        // TODO add your handling code here: Cadastra novo PodCast
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            String nomeProdutor = txtNomeProdutor.getText();
            String nomeEpisodio = txtNomeEpisodio.getText();
            int numeroEpisodio = Integer.parseInt(txtNumeroEpisodio.getText());
            int duracao = Integer.parseInt(txtDuracao.getText());
            String url = txtURL.getText();

            Podcast novoPodcast = new Podcast(0, nomeProdutor, nomeEpisodio, numeroEpisodio, duracao, url);
            Database database = new Database(); 
            database.adicionarPodcast(novoPodcast);
            
            System.out.println("Cadastrado com sucesso! ");
            // Limpa os campos de texto para uma nova entrada
        txtNomeProdutor.setText("");
        txtNomeEpisodio.setText("");
        txtNumeroEpisodio.setText("");
        txtDuracao.setText("");
        txtURL.setText("");
            
            txtNomeProdutor.requestFocus();
        }
    }//GEN-LAST:event_btnCadastrarPodKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPodcast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPodcast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarPod;
    private javax.swing.JButton btnVerListagem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadastrarPodCast;
    private javax.swing.JLabel lblCenaflix3;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblNomeEpsodio;
    private javax.swing.JLabel lblNumeroEpisodio;
    private javax.swing.JLabel lblPodCast3;
    private javax.swing.JLabel lblProdutorCad;
    private javax.swing.JLabel lblURL;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtNomeEpisodio;
    private javax.swing.JTextField txtNomeProdutor;
    private javax.swing.JTextField txtNumeroEpisodio;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
