/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import models.Usuario;
import views.Listagem;



/**
 *
 * @author Familia Brasileiro
 */
public class Login extends javax.swing.JFrame {
    private Map<String, Usuario> usuarios = new HashMap<>();
    
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        usuarios.put("admin", new Usuario("admin", "1234", "Administrador"));
        usuarios.put("operador", new Usuario("operador", "1234", "Operador"));
        usuarios.put("usuario", new Usuario("usuario", "1234", "Usuário"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCenaflix = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblPodCast = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Br Software");

        jPanel1.setBackground(new java.awt.Color(10, 8, 29));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("TelaLogin"));
        jPanel1.setToolTipText("Tela de Login");
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCenaflix.setBackground(new java.awt.Color(0, 0, 0));
        lblCenaflix.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblCenaflix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCenaflix.setText("CENAFLIX");
        lblCenaflix.setToolTipText("CenaFlix");
        jPanel1.add(lblCenaflix, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 500, 60));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(238, 86, 153));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login");
        lblLogin.setToolTipText("Login");
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, -1));

        txtLogin.setBackground(new java.awt.Color(143, 205, 240));
        txtLogin.setToolTipText("Digite seu Login");
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 390, 30));

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(238, 86, 153));
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setText("Senha");
        lblSenha.setToolTipText("Senha");
        jPanel1.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 60, -1));

        txtPassword.setBackground(new java.awt.Color(143, 205, 240));
        txtPassword.setToolTipText("Informe sua Senha");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 390, 30));

        btnLogin.setBackground(new java.awt.Color(143, 205, 240));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(238, 86, 153));
        btnLogin.setText("LOGIN");
        btnLogin.setToolTipText("Botão de Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        lblPodCast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPodCast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PodCast.jpg"))); // NOI18N
        lblPodCast.setToolTipText("Imagem PodCast");
        jPanel1.add(lblPodCast, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 190, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here: Botão de Login
        // Recupera o usuário e a senha dos campos de texto
    String username = txtLogin.getText().toLowerCase();
    String password = new String(txtPassword.getPassword());

    // Verifica se o usuário existe e se a senha está correta
    if (usuarios.containsKey(username) && usuarios.get(username).getPassword().equalsIgnoreCase(password)) {
        // Recupera o objeto Usuario correspondente ao username
       Usuario usuario = usuarios.get(username);
        // Verifica o tipo de usuário e ajusta as permissões da interface
        if (usuarios.containsKey(username) && usuarios.get(username).getPassword().equalsIgnoreCase(password)) {
          usuario  = usuarios.get(username);
          //String tipoUsuario = usuario.getTipo();
          
          switch(username) {
              case "admin" :
                  JOptionPane.showMessageDialog(Login.this, 
                "Olá " + usuario.getUsuario() + ", sua permissão é de: Lista, Excluir, Cadastrar\n  " + usuario.getTipo() + ". Seja bem-vindo!");
                 
                  // abrirTelaPrincipal(usuario);
            Listagem telaListagem = new Listagem(usuario);  // Passe o usuário como parâmetro
            
            
            telaListagem.setVisible(true);
            dispose();
            break;
            
              case "operador":
                   JOptionPane.showMessageDialog(Login.this, 
                "Olá " + usuario.getUsuario().equalsIgnoreCase("operador") + ", sua permissão é de: Lista, Cadastrar\n  " + usuario.getTipo() + ". Seja bem-vindo!");
                  
                   // abrirTelaPrincipal(usuario);
            Listagem telaListagem1 = new Listagem(usuario);  // Passe o usuário como parâmetro
            telaListagem1.setVisible(true);
            dispose();
            break;
            
             case "usuario":
                  JOptionPane.showMessageDialog(Login.this, 
                "Olá " + usuario.getUsuario() + ", sua permissão é de: Lista\n  " + usuario.getTipo() + ". Seja bem-vindo!");
                  Listagem telaListagem2 = new Listagem(usuario);  // Passe o usuário como parâmetro
            telaListagem2.setVisible(true);
            dispose();
            break;
           
            default:
                JOptionPane.showMessageDialog(this, 
                        "Tipo de usuário não reconhecido!", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            }
        } 
    } else {
        // Se o usuário ou senha estiverem incorretos, exibe uma mensagem de erro
        JOptionPane.showMessageDialog(this, 
            "Usuário ou senha inválidos", "Erro", JOptionPane.ERROR_MESSAGE);
        }
               
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        // TODO add your handling code here: Avançar para senha
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        // Move o foco para o campo txtSenha
        txtPassword.requestFocusInWindow();
    }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        btnLogin.requestFocusInWindow();
    }

    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        // TODO add your handling code here: Avança para tela Listagem
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            String username = txtLogin.getText();
            String password = new String(txtPassword.getPassword());
            
             // Verifica se os campos estão preenchidos
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            // Verifica se o usuário existe e se a senha está correta
            if (usuarios.containsKey(username) && usuarios.get(username).getPassword().equals(password)) {
            // Recupera o usuário e avança para a tela de Listagem
            Usuario usuario = usuarios.get(txtLogin.getText());
            JOptionPane.showMessageDialog(Login.this, 
                "Olá " + usuario.getUsuario() + ", sua permissão é de: Lista\n  " + usuario.getTipo() + ". Seja bem-vindo!");
                  Listagem telaListagem = new Listagem(usuario);  // Passe o usuário como parâmetro
                  if (usuario.getTipo().equalsIgnoreCase("usuario")) {
                        telaListagem.setVisibilidadeBotoes(true, false, false);
                    } else if (usuario.getTipo().equalsIgnoreCase("operador")) {
                        telaListagem.setVisibilidadeBotoes(true, true, false);
            } else if (usuario.getTipo().equalsIgnoreCase("admin")) {
                        telaListagem.setVisibilidadeBotoes(true, true, true);
        }

                  
                  telaListagem.setVisible(true);
            dispose();
            
            
            
            /*Listagem telaListagem = new Listagem(usuario);
            telaListagem.setVisible(true);
            dispose();*/
            }else {
                // Se o usuário ou a senha estiverem incorretos, exibe uma mensagem de erro
                JOptionPane.showMessageDialog(this, 
                    "Usuário ou senha inválidos", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_btnLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCenaflix;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPodCast;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
